
import { 
  archivo_narrow, 
  dm_sans, 
  dm_serif_display, 
  fira_sans, 
  fjalla_one, 
  inter, 
  josefin_sans, 
  nunito, 
  poppins, 
  roboto_mono, 
  rubik, 
  syne 
} from "@/utils/font";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getLocale } from "next-intl/server";

export const metadata = {
  title: "Resume Maker",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const messages = await getMessages()
  const locale = await getLocale();
  return (
    <html lang={locale} data-theme="light">
        <body className={`antialiased 
          ${nunito} 
          ${archivo_narrow}
          ${syne} 
          ${dm_serif_display}
          ${dm_sans} 
          ${poppins}
          ${rubik}
          ${fira_sans}
          ${josefin_sans}
          ${roboto_mono}
          ${fjalla_one}
          ${inter}
        `}
          >
            <StoreProvider>
              <NextIntlClientProvider messages={messages}>
                  {children}
              </NextIntlClientProvider>
            </StoreProvider>
        </body>
      </html>
  );
}
